package core.upcraftlp.craftdev.proxy;

import java.util.Arrays;

import core.upcraftlp.craftdev.client.MobScaleHandler;
import core.upcraftlp.craftdev.common.CraftDevReference;
import core.upcraftlp.craftdev.config.CoreInternalConfig;
import net.minecraft.client.Minecraft;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;

public class ClientProxy extends CommonProxy {

    @Override
    public void preInit(FMLPreInitializationEvent event) {
        super.preInit(event);
        
        ModMetadata data = event.getModMetadata();
        data.autogenerated = false;
        data.authorList = Arrays.asList(CraftDevReference.authors);
        data.credits = CraftDevReference.CREDITS;
        data.modId = CraftDevReference.MODID;
        data.name = CraftDevReference.MODNAME;
        data.description = CraftDevReference.MOD_DESCRIPTION;
        data.url = CraftDevReference.UPDATE_URL;
        data.updateJSON = CraftDevReference.UPDATE_JSON;
    }
    
    @Override
    public void init(FMLInitializationEvent event) {
        super.init(event);
    }
    
    @Override
    public void postInit(FMLPostInitializationEvent event) {
        super.postInit(event);
    }
    
    @Override
    public void serverStarting(FMLServerStartingEvent event) {
        super.serverStarting(event);
    }
    
    @Override
    public void configChanged() {
        super.configChanged();
        float mobScaleFactor = CoreInternalConfig.mobScaleFactor;
        boolean enabled = mobScaleFactor > 0.0f;
        MobScaleHandler.isEnabled = enabled;
        MobScaleHandler.scalePlayers = CoreInternalConfig.scalePlayers;
        MobScaleHandler.scale = mobScaleFactor;
        Minecraft.getMinecraft().gameSettings.entityShadows = !enabled;
    }
}
